### ISSUE TITLE
기업 추가하고 싶습니다: 코드잇

### ISSUE THREAD

**Issue by jts04** [sooftware/k-startups#1]
비전공자와 개발자 준비생을 주요 타겟으로 하는 온라인 코딩 교육 서비스. 개별 강의 판매가 아닌 구독형 멤버십이다. 모든 강의를 내부에서 직접 제작하여 퀄리티 컨트롤을 하고 있으며, 별도 설치 없이 브라우저 내 코딩 실습이 가능한 플랫폼을 제공한다. 누적 140억 원의 투자를 유치했다.

추가 검토 부탁드립니다 :)

**Comment by sooftware** [comment]
아 네 감사합니다! 추가하겠습니다 :)

2022년 3월 28일 (월) 오후 6:11, jts04 ***@***.***>님이 작성:

**Comment by sooftware** [comment]
추가 완료했습니다.  
이슈는 클로징 하겠습니다 :)
